plugins {
    id 'org.quiltmc.loom' version '1.4.1'
    id 'maven-publish'
}

version = "${mod_version}+mc${minecraft_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

sourceSets.main.java.srcDirs = ['ports/fabric-1.20.1/src/main/java']
sourceSets.main.resources.srcDirs = ['ports/fabric-1.20.1/src/main/resources']

loom {
    mods {
        magnot {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.quiltmc.org/repository/release/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        mappings "org.quiltmc:quilt-mappings:${quilt_mappings_version}:intermediary-v2"
        officialMojangMappings()
    }
    modImplementation "org.quiltmc:quilt-loader:${quilt_loader_version}"
    modImplementation "org.quiltmc.quilted-fabric-api:quilted-fabric-api:${qfapi_version}"
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
    from('src/main/resources') {
        include 'assets/**'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
