modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="magnot.png"
logoBlur=false
description='''${mod_description}'''

[[mixins]]
config="magnot.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedcore"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedstorage"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2wtlib"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="projecte"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botania"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="artifacts"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="draconicevolution"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="reliquary"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="actuallyadditions"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mob_grinding_utils"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="itemcollectors"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simplemagnets"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="modularrouters"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="enderio"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sable"
type="optional"
ordering="AFTER"
side="BOTH"
