modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="magnot"
version="${version}"
displayName="Magnot"
authors="beeboee"
description='''Ferrous regions that block supported remote item pulls.'''

[[dependencies.magnot]]
modId="forge"
mandatory=true
versionRange="[40.2.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.magnot]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.18.3)"
ordering="NONE"
side="BOTH"

[[dependencies.magnot]]
modId="create"
mandatory=true
versionRange="[0.5.1,0.6.0)"
ordering="AFTER"
side="BOTH"
