modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="magnot"
version="${version}"
displayName="Magnot"
authors="beeboee"
description='''Create-style ferrous regions that block supported magnets and vacuum effects from pulling dropped items through protected areas.'''

[[dependencies.magnot]]
modId="forge"
mandatory=true
versionRange="[47.1.33,)"
ordering="NONE"
side="BOTH"

[[dependencies.magnot]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.magnot]]
modId="create"
mandatory=true
versionRange="[0.5.1,)"
ordering="AFTER"
side="BOTH"
